#############################################################################
# Makefile for building: GUI_Editor
# Generated by qmake (1.07a) (Qt 3.3.5) on: Mon Jan  9 10:16:08 2006
# Project:  GUI_Editor.pro
# Template: app
# Command: $(QMAKE) -o Makefile GUI_Editor.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT
CXXFLAGS = -pipe -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d -DXTHREADS
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -IGUI_Command -ITesting -I/usr/share/qt3/include -I/usr/local/include -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/X11R6/include -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lXext -lX11 -lm -lpthread -L/usr/local/lib -lcppunit -ldl -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgdk_pixbuf-2.0 -lm -lpangoxft-1.0 -lpangox-1.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lgmodule-2.0 -ldl -lglib-2.0
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = Clipboard.h \
		Cursor.h \
		Cursor_Imp.h \
		Display.h \
		Display_Imp.h \
		Exception.h \
		GUI_Comm_Win.h \
		GUI_DialogMaker.h \
		GUI_InfoDialog.h \
		GUI_Interface.h \
		GUI_Menu.h \
		Input.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		LineBreak.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		Location.h \
		Multiquery.h \
		Query.h \
		QueryWord.h \
		SpellChecker.h \
		StateMgr.h \
		Step.h \
		StepHandler.h \
		Text.h \
		Text_Imp.h \
		TextEditorApp.h \
		TextLocationMap.h \
		TextLocationMap_Imp.h \
		TextLocationMapBuilder.h \
		TextLocationMapBuilder_Imp.h \
		Tokener.h \
		WrongNumberOfArgumentsException.h \
		GUI_Command/Command.h \
		GUI_Command/Edit_InsertFile.h \
		GUI_Command/File_Open.h \
		GUI_Command/File_Save.h \
		Testing/Cursor_Mock.h \
		Testing/Display_Mock.h \
		Testing/InputTest.h \
		Testing/LineBreak_Div_Test.h \
		Testing/LineBreak_Pre_Test.h \
		Testing/Location_Mock.h \
		Testing/LocationTest.h \
		Testing/Multiquery_Test.h \
		Testing/Query_Test.h \
		Testing/SpellChecker_Test.h \
		Testing/StateMgr_Test.h \
		Testing/Text_Test.h \
		Testing/TextLocationMap_Mock.h \
		Testing/TextLocationMap_Test.h \
		Testing/TextLocationMapBuilder_Mock.h \
		Testing/TextLocationMapBuilderTest.h \
		Testing/TokenerTest.h
SOURCES = Clipboard.cpp \
		Cursor_Imp.cpp \
		Display_Imp.cpp \
		Exception.cpp \
		GUI_Comm_Win.cpp \
		GUI_DialogMaker.cpp \
		GUI_InfoDialog.cpp \
		GUI_Interface.cpp \
		GUI_Menu.cpp \
		Input.cpp \
		InvalidArgumentException.cpp \
		InvalidLocationException.cpp \
		LineBreak_Div.cpp \
		LineBreak_Pre.cpp \
		Location.cpp \
		Main.cpp \
		Multiquery.cpp \
		Query.cpp \
		QueryWord.cpp \
		SpellChecker.cpp \
		StateMgr.cpp \
		Step.cpp \
		StepHandler.cpp \
		Text_Imp.cpp \
		TextEditorApp.cpp \
		TextLocationMap_Imp.cpp \
		TextLocationMapBuilder_Imp.cpp \
		Tokener.cpp \
		WrongNumberOfArgumentsException.cpp \
		GUI_Command/Command.cpp \
		GUI_Command/Edit_InsertFile.cpp \
		GUI_Command/File_Open.cpp \
		GUI_Command/File_Save.cpp \
		Testing/Cursor_Mock.cpp \
		Testing/Display_Mock.cpp \
		Testing/InputTest.cpp \
		Testing/LineBreak_Div_Test.cpp \
		Testing/LineBreak_Pre_Test.cpp \
		Testing/Location_Mock.cpp \
		Testing/LocationTest.cpp \
		Testing/Multiquery_Test.cpp \
		Testing/Query_Test.cpp \
		Testing/SpellChecker_Test.cpp \
		Testing/StateMgr_Test.cpp \
		Testing/Text_Test.cpp \
		Testing/TextLocationMap_Mock.cpp \
		Testing/TextLocationMap_Test.cpp \
		Testing/TextLocationMapBuilder_Mock.cpp \
		Testing/TextLocationMapBuilderTest.cpp \
		Testing/TokenerTest.cpp
OBJECTS = Clipboard.o \
		Cursor_Imp.o \
		Display_Imp.o \
		Exception.o \
		GUI_Comm_Win.o \
		GUI_DialogMaker.o \
		GUI_InfoDialog.o \
		GUI_Interface.o \
		GUI_Menu.o \
		Input.o \
		InvalidArgumentException.o \
		InvalidLocationException.o \
		LineBreak_Div.o \
		LineBreak_Pre.o \
		Location.o \
		Main.o \
		Multiquery.o \
		Query.o \
		QueryWord.o \
		SpellChecker.o \
		StateMgr.o \
		Step.o \
		StepHandler.o \
		Text_Imp.o \
		TextEditorApp.o \
		TextLocationMap_Imp.o \
		TextLocationMapBuilder_Imp.o \
		Tokener.o \
		WrongNumberOfArgumentsException.o \
		Command.o \
		Edit_InsertFile.o \
		File_Open.o \
		File_Save.o \
		Cursor_Mock.o \
		Display_Mock.o \
		InputTest.o \
		LineBreak_Div_Test.o \
		LineBreak_Pre_Test.o \
		Location_Mock.o \
		LocationTest.o \
		Multiquery_Test.o \
		Query_Test.o \
		SpellChecker_Test.o \
		StateMgr_Test.o \
		Text_Test.o \
		TextLocationMap_Mock.o \
		TextLocationMap_Test.o \
		TextLocationMapBuilder_Mock.o \
		TextLocationMapBuilderTest.o \
		TokenerTest.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = 
OBJMOC = 
DIST	   = GUI_Editor.pro
QMAKE_TARGET = GUI_Editor
DESTDIR  = 
TARGET   = GUI_Editor

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: GUI_Editor.pro  /usr/share/qt3/mkspecs/default/qmake.conf 
	$(QMAKE) -o Makefile GUI_Editor.pro
qmake: 
	@$(QMAKE) -o Makefile GUI_Editor.pro

dist: 
	@mkdir -p .tmp/GUI_Editor && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/GUI_Editor/ && ( cd `dirname .tmp/GUI_Editor` && $(TAR) GUI_Editor.tar GUI_Editor && $(GZIP) GUI_Editor.tar ) && $(MOVE) `dirname .tmp/GUI_Editor`/GUI_Editor.tar.gz . && $(DEL_FILE) -r .tmp/GUI_Editor

mocclean:

uiclean:

yaccclean:
lexclean:
clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

Clipboard.o: Clipboard.cpp Clipboard.h

Cursor_Imp.o: Cursor_Imp.cpp Cursor_Imp.h \
		Display.h \
		Cursor.h \
		Location.h \
		StateMgr.h

Display_Imp.o: Display_Imp.cpp Display_Imp.h \
		Display.h \
		GUI_Interface.h \
		GUI_InfoDialog.h \
		StateMgr.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h

Exception.o: Exception.cpp Exception.h

GUI_Comm_Win.o: GUI_Comm_Win.cpp GUI_Comm_Win.h \
		Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		GUI_Interface.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_Menu.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h

GUI_DialogMaker.o: GUI_DialogMaker.cpp GUI_DialogMaker.h \
		Input.h \
		Cursor_Imp.h \
		GUI_Menu.h \
		StepHandler.h \
		Text_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		GUI_Interface.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_Comm_Win.h \
		Step.h

GUI_InfoDialog.o: GUI_InfoDialog.cpp GUI_InfoDialog.h

GUI_Interface.o: GUI_Interface.cpp GUI_Interface.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h

GUI_Menu.o: GUI_Menu.cpp GUI_Menu.h \
		GUI_Comm_Win.h \
		GUI_DialogMaker.h \
		Input.h \
		Cursor_Imp.h \
		StepHandler.h \
		Text_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		GUI_Interface.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		Step.h

Input.o: Input.cpp Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		GUI_Interface.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h

InvalidArgumentException.o: InvalidArgumentException.cpp InvalidArgumentException.h \
		Exception.h

InvalidLocationException.o: InvalidLocationException.cpp InvalidLocationException.h \
		Exception.h \
		Location.h

LineBreak_Div.o: LineBreak_Div.cpp LineBreak_Div.h \
		LineBreak.h \
		Tokener.h

LineBreak_Pre.o: LineBreak_Pre.cpp LineBreak_Pre.h \
		LineBreak.h \
		Tokener.h

Location.o: Location.cpp Location.h

Main.o: Main.cpp TextEditorApp.h \
		Text_Imp.h \
		Display_Imp.h \
		Input.h \
		Cursor_Imp.h \
		SpellChecker.h \
		GUI_Interface.h \
		StateMgr.h \
		StepHandler.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Tokener.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		GUI_InfoDialog.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		WrongNumberOfArgumentsException.h \
		LineBreak.h \
		GUI_DialogMaker.h \
		Step.h

Multiquery.o: Multiquery.cpp Multiquery.h \
		Tokener.h \
		Display.h \
		Query.h \
		QueryWord.h \
		TextLocationMap_Imp.h \
		TextLocationMapBuilder_Imp.h \
		TextLocationMap.h \
		Location.h \
		TextLocationMapBuilder.h

Query.o: Query.cpp Query.h \
		Tokener.h

QueryWord.o: QueryWord.cpp QueryWord.h \
		Tokener.h \
		TextLocationMap_Imp.h \
		TextLocationMapBuilder_Imp.h \
		TextLocationMap.h \
		Location.h \
		Query.h \
		TextLocationMapBuilder.h

SpellChecker.o: SpellChecker.cpp SpellChecker.h \
		Display.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMapBuilder.h \
		TextLocationMap_Imp.h \
		TextLocationMap.h \
		Query.h \
		Tokener.h

StateMgr.o: StateMgr.cpp StateMgr.h

Step.o: Step.cpp Step.h \
		Cursor.h \
		SpellChecker.h \
		Text.h \
		Location.h \
		Display.h \
		StateMgr.h \
		TextLocationMapBuilder_Imp.h \
		TextLocationMapBuilder.h \
		TextLocationMap_Imp.h \
		TextLocationMap.h \
		Query.h \
		Tokener.h

StepHandler.o: StepHandler.cpp StepHandler.h \
		Cursor.h \
		SpellChecker.h \
		Text.h \
		Step.h \
		Location.h \
		Display.h \
		StateMgr.h \
		TextLocationMapBuilder_Imp.h \
		TextLocationMapBuilder.h \
		TextLocationMap_Imp.h \
		TextLocationMap.h \
		Query.h \
		Tokener.h

Text_Imp.o: Text_Imp.cpp Text_Imp.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Cursor_Imp.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Tokener.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		StateMgr.h \
		QueryWord.h \
		Exception.h

TextEditorApp.o: TextEditorApp.cpp TextEditorApp.h \
		Text_Imp.h \
		Display_Imp.h \
		Input.h \
		Cursor_Imp.h \
		SpellChecker.h \
		GUI_Interface.h \
		StateMgr.h \
		StepHandler.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Tokener.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		GUI_InfoDialog.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		WrongNumberOfArgumentsException.h \
		LineBreak.h \
		GUI_DialogMaker.h \
		Step.h

TextLocationMap_Imp.o: TextLocationMap_Imp.cpp TextLocationMap_Imp.h \
		TextLocationMap.h \
		Location.h \
		Query.h \
		Tokener.h

TextLocationMapBuilder_Imp.o: TextLocationMapBuilder_Imp.cpp TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMapBuilder.h \
		TextLocationMap_Imp.h \
		TextLocationMap.h \
		Query.h \
		Tokener.h

Tokener.o: Tokener.cpp Tokener.h

WrongNumberOfArgumentsException.o: WrongNumberOfArgumentsException.cpp WrongNumberOfArgumentsException.h \
		Exception.h

Command.o: GUI_Command/Command.cpp GUI_Command/Command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Command.o GUI_Command/Command.cpp

Edit_InsertFile.o: GUI_Command/Edit_InsertFile.cpp GUI_Command/Edit_InsertFile.h \
		GUI_Command/Command.h \
		Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		GUI_Interface.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Edit_InsertFile.o GUI_Command/Edit_InsertFile.cpp

File_Open.o: GUI_Command/File_Open.cpp GUI_Command/File_Open.h \
		GUI_Command/Command.h \
		Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		GUI_Interface.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o File_Open.o GUI_Command/File_Open.cpp

File_Save.o: GUI_Command/File_Save.cpp GUI_Command/File_Save.h \
		GUI_Command/Command.h \
		Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		GUI_Interface.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Display.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o File_Save.o GUI_Command/File_Save.cpp

Cursor_Mock.o: Testing/Cursor_Mock.cpp Testing/Cursor_Mock.h \
		Display.h \
		Cursor.h \
		Location.h \
		StateMgr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cursor_Mock.o Testing/Cursor_Mock.cpp

Display_Mock.o: Testing/Display_Mock.cpp Testing/Display_Mock.h \
		Display.h \
		GUI_Interface.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		Tokener.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		TextLocationMap_Imp.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Display_Mock.o Testing/Display_Mock.cpp

InputTest.o: Testing/InputTest.cpp Testing/InputTest.h \
		Input.h \
		Display.h \
		Text.h \
		Tokener.h \
		Text_Imp.h \
		Cursor_Imp.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		GUI_Interface.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		TextLocationMap_Imp.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Cursor.h \
		Query.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o InputTest.o Testing/InputTest.cpp

LineBreak_Div_Test.o: Testing/LineBreak_Div_Test.cpp Testing/LineBreak_Div_Test.h \
		LineBreak_Div.h \
		LineBreak.h \
		Tokener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LineBreak_Div_Test.o Testing/LineBreak_Div_Test.cpp

LineBreak_Pre_Test.o: Testing/LineBreak_Pre_Test.cpp Testing/LineBreak_Pre_Test.h \
		LineBreak_Pre.h \
		LineBreak.h \
		Tokener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LineBreak_Pre_Test.o Testing/LineBreak_Pre_Test.cpp

Location_Mock.o: Testing/Location_Mock.cpp Testing/Location_Mock.h \
		Location.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Location_Mock.o Testing/Location_Mock.cpp

LocationTest.o: Testing/LocationTest.cpp Testing/LocationTest.h \
		Location.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LocationTest.o Testing/LocationTest.cpp

Multiquery_Test.o: Testing/Multiquery_Test.cpp Testing/Multiquery_Test.h \
		Multiquery.h \
		Tokener.h \
		Display.h \
		Query.h \
		QueryWord.h \
		TextLocationMap_Imp.h \
		TextLocationMapBuilder_Imp.h \
		TextLocationMap.h \
		Location.h \
		TextLocationMapBuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Multiquery_Test.o Testing/Multiquery_Test.cpp

Query_Test.o: Testing/Query_Test.cpp Testing/Query_Test.h \
		Query.h \
		Tokener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Query_Test.o Testing/Query_Test.cpp

SpellChecker_Test.o: Testing/SpellChecker_Test.cpp Testing/SpellChecker_Test.h \
		SpellChecker.h \
		Testing/Display_Mock.h \
		Display.h \
		TextLocationMapBuilder_Imp.h \
		Location.h \
		TextLocationMapBuilder.h \
		TextLocationMap_Imp.h \
		TextLocationMap.h \
		Query.h \
		Tokener.h \
		GUI_Interface.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		StateMgr.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Text.h \
		Multiquery.h \
		Cursor.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpellChecker_Test.o Testing/SpellChecker_Test.cpp

StateMgr_Test.o: Testing/StateMgr_Test.cpp Testing/StateMgr_Test.h \
		StateMgr.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StateMgr_Test.o Testing/StateMgr_Test.cpp

Text_Test.o: Testing/Text_Test.cpp Testing/Text_Test.h \
		Text.h \
		Testing/Display_Mock.h \
		Testing/Cursor_Mock.h \
		Location.h \
		TextLocationMap.h \
		TextLocationMapBuilder.h \
		Display.h \
		Cursor.h \
		Tokener.h \
		TextLocationMap_Imp.h \
		Query.h \
		StateMgr.h \
		GUI_Interface.h \
		GUI_Comm_Win.h \
		GUI_Menu.h \
		Input.h \
		Text_Imp.h \
		Cursor_Imp.h \
		SpellChecker.h \
		LineBreak_Div.h \
		LineBreak_Pre.h \
		WrongNumberOfArgumentsException.h \
		InvalidArgumentException.h \
		InvalidLocationException.h \
		Multiquery.h \
		TextLocationMapBuilder_Imp.h \
		QueryWord.h \
		Exception.h \
		LineBreak.h \
		GUI_DialogMaker.h \
		StepHandler.h \
		Step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Text_Test.o Testing/Text_Test.cpp

TextLocationMap_Mock.o: Testing/TextLocationMap_Mock.cpp Testing/TextLocationMap_Mock.h \
		Testing/Location_Mock.h \
		TextLocationMap.h \
		Location.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextLocationMap_Mock.o Testing/TextLocationMap_Mock.cpp

TextLocationMap_Test.o: Testing/TextLocationMap_Test.cpp Testing/TextLocationMap_Test.h \
		TextLocationMap_Imp.h \
		TextLocationMap.h \
		Location.h \
		Query.h \
		Tokener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextLocationMap_Test.o Testing/TextLocationMap_Test.cpp

TextLocationMapBuilder_Mock.o: Testing/TextLocationMapBuilder_Mock.cpp Testing/TextLocationMapBuilder_Mock.h \
		Location.h \
		TextLocationMapBuilder.h \
		TextLocationMap.h \
		TextLocationMap_Imp.h \
		Query.h \
		Tokener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextLocationMapBuilder_Mock.o Testing/TextLocationMapBuilder_Mock.cpp

TextLocationMapBuilderTest.o: Testing/TextLocationMapBuilderTest.cpp Testing/TextLocationMapBuilderTest.h \
		Location.h \
		TextLocationMapBuilder_Imp.h \
		Testing/TextLocationMap_Mock.h \
		TextLocationMapBuilder.h \
		TextLocationMap_Imp.h \
		TextLocationMap.h \
		Query.h \
		Tokener.h \
		Testing/Location_Mock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TextLocationMapBuilderTest.o Testing/TextLocationMapBuilderTest.cpp

TokenerTest.o: Testing/TokenerTest.cpp Testing/TokenerTest.h \
		Tokener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TokenerTest.o Testing/TokenerTest.cpp

####### Install

install:  

uninstall:  

