// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEXTLOCATIONMAP_IMP_H
#define TEXTLOCATIONMAP_IMP_H

#include <vector>
#include <string>
#include <utility>
#include "TextLocationMap.h"
#include "Location.h"
#include "Query.h"

using namespace std;

typedef vector<Location> LocationSet;
typedef vector<pair<string,LocationSet> > ErrorSet;

class TextLocationMap_Imp : public TextLocationMap
{
public:
    void add(string words, vector<Location> locs);
    string dump();
    LocationSet* getLocationSet(string word);
    ErrorSet* getErrorSet(vector<string> *m_pDict);
    vector<string>* getWord();
    vector<LocationSet>* getLocations();
public:
	// class constructor
	TextLocationMap_Imp();
	// class destructor
	~TextLocationMap_Imp();
private:
    vector<string>* _words;
    vector<LocationSet> *_locs;
};

#endif // TEXTLOCATIONMAP_IMP_H
