// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEXTLOCATIONMAPBUILDER_H
#define TEXTLOCATIONMAPBUILDER_H

#include <vector>
#include <string>
#include "Location.h"
#include "TextLocationMap_Imp.h"

using namespace std;

class TextLocationMapBuilder
{
public:
	// class constructor
	TextLocationMapBuilder(){}
	// class destructor
	virtual ~TextLocationMapBuilder(){}
	static const string filt_elems;
	virtual TextLocationMap* build(vector<string>* lines_of_text,bool suffix=true)=0;
	virtual void TextLocationMapBuilder::loadExclude(vector<string>* lines_of_text)=0;
	virtual void separate_words(vector<string>* lines_of_text, vector<string>* words, vector<Location>* locs)=0;
	virtual void filter_text(vector<string>* words)=0;
	virtual void suffix_text(vector<string>* words)=0;
	virtual void strip_cap(vector<string>* words)=0;
	virtual void sort_text(vector<string>* words, vector<Location>* locs)=0;
	virtual void exclude_text(vector<string>* words )=0;
	virtual TextLocationMap* build_location_map(vector<string>* words, vector<Location>* locs)=0;
	vector<string> exclude_words;
};

#endif // TEXTLOCATIONMAPBUILDER_H
