// Class automatically generated by Dev-C++ New Class wizard

#ifndef TEXTLOCATIONMAPBUILDER_IMP_H
#define TEXTLOCATIONMAPBUILDER_IMP_H

#include <vector>
#include <string>
#include "Location.h"
#include "TextLocationMapBuilder.h"
#include "TextLocationMap_Imp.h"

using namespace std;

class TextLocationMapBuilder_Imp : public TextLocationMapBuilder
{
public:
	static const string filt_elems;
	TextLocationMap* build(vector<string>* lines_of_text,bool suffix=true);
	void TextLocationMapBuilder_Imp::loadExclude(vector<string>* lines_of_text);
public:
	// class constructor
	TextLocationMapBuilder_Imp();
	// class destructor
	~TextLocationMapBuilder_Imp();
private:
	void separate_words(vector<string>* lines_of_text, vector<string>* words, vector<Location>* locs);
	void filter_text(vector<string>* words);
	void suffix_text(vector<string>* words);
	void strip_cap(vector<string>* words);
	void sort_text(vector<string>* words, vector<Location>* locs);
	void exclude_text(vector<string>* words );
	TextLocationMap* build_location_map(vector<string>* words, vector<Location>* locs);
	vector<string> exclude_words;
};

#endif // TEXTLOCATIONMAPBUILDER_IMP_H
